### ISSUE TITLE
bug: []*struct 

### ISSUE THREAD

**Issue by fitan** [StirlingMarketingGroup/go2ts#1]
![image](https://user-images.githubusercontent.com/34503273/128660364-ee361787-ed04-484f-8fd6-6923f4630974.png)

**Comment by BrianLeishman** [comment]
Not entirely sure what you're asking/pointing out?

**Comment by BrianLeishman** [comment]
I see a bug here, and a pr that fixes it has been created, if that's the issue you were referring to then it should be fixed

![image](https://user-images.githubusercontent.com/1208702/128869964-594d09e3-5596-4463-90bc-be5ae41cef43.png)
